[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "graph-py"
version = "0.1.0"
description = "A Python library for graph algorithms and data structures."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name="Bastian Lipka" }
]
dependencies = [
  "networkx>=3.0",
  "numpy>=1.23",
  "matplotlib>=3.7",
  "pydantic>=1.10,<3",
]
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
  "pytest>=8.0",
  "pytest-cov>=5.0",
  "ruff>=0.5.0",
  "black>=24.3",
  "mypy>=1.10",
]

[project.urls]
Homepage = "https://github.com/kirbs-btw/graph-py"
Issues = "https://github.com/kirbs-btw/graph-py/issues"

[tool.pytest.ini_options]
pythonpath = ["src"]
